"""StorageBackend protocol."""

from __future__ import annotations

import uuid
from typing import Any, Optional, Protocol, runtime_checkable

from ..models.evidence import Claim, EvidenceItem, VerificationResult
from ..models.execution import RunCheckpoint, ToolCallRecord
from ..models.output import ResearchReport, SessionSummary
from ..models.plan import ResearchPlan
from ..models.session import SessionConfig
from ..models.skill import DeploymentRecord, DynamicSkillSpec


@runtime_checkable
class StorageBackend(Protocol):
    async def create_session(self, config: SessionConfig) -> str: ...
    async def load_session(self, session_id: str) -> Optional[SessionConfig]: ...
    async def save_skill(self, skill: DynamicSkillSpec) -> None: ...
    async def load_skill(self, session_id: str) -> Optional[DynamicSkillSpec]: ...
    async def save_deployment(self, record: DeploymentRecord) -> None: ...
    async def save_plan(self, plan: ResearchPlan) -> None: ...
    async def load_plan(self, session_id: str) -> Optional[ResearchPlan]: ...
    async def insert_tool_call(self, record: ToolCallRecord) -> None: ...
    async def get_tool_calls(self, session_id: str) -> list[ToolCallRecord]: ...
    async def insert_evidence(self, item: EvidenceItem) -> None: ...
    async def get_evidence(self, session_id: str) -> list[EvidenceItem]: ...
    async def insert_claim(self, claim: Claim) -> None: ...
    async def get_claims(self, session_id: str) -> list[Claim]: ...
    async def insert_verification(self, result: VerificationResult) -> None: ...
    async def get_verifications(self, session_id: str) -> list[VerificationResult]: ...
    async def save_report(self, report: ResearchReport) -> None: ...
    async def load_report(self, session_id: str) -> Optional[ResearchReport]: ...
    async def save_checkpoint(self, checkpoint: RunCheckpoint) -> None: ...
    async def load_latest_checkpoint(self, session_id: str) -> Optional[RunCheckpoint]: ...
    async def save_summary(self, summary: SessionSummary) -> None: ...
    async def list_sessions(self) -> list[dict[str, Any]]: ...
    async def list_skills(self) -> list[dict[str, Any]]: ...
    async def find_skill(self, name_or_id: str) -> Optional[dict[str, Any]]: ...
